VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.box = "trusty64"
config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
config.vm.synced_folder "./", "/vagrant", id: "vagrant-root"
config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
end
config.vm.provision :puppet do |puppet|
puppet.manifests_path = "manifests"
puppet.options = ['--verbose']
puppet.manifest_file = "hadoop-setup.pp"
end
config.vm.define :setVars do |setVars|
setVars.vm.provision :shell, :path => "provision_box.sh"
end
config.vm.provision "shell", inline: "source /etc/environment"
end  
